os: linux
dist: focal
language: python
python: "3.9"
arch: arm64-graviton2

jobs:
  include:
  - arch: arm64-graviton2
    virt: vm
    group: edge
  - arch: ppc64le
  - arch: s390x
  allow_failures:
  - arch: ppc64le

addons:
  apt:
    packages:
    - qemu-user-binfmt

services:
  - docker

notifications:
  email: false

install:
  - pwd
  - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
  - curl -fsSLo ${HOME}/codecov.SHA256SUM https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
  - curl -fsSLo ${HOME}/codecov.SHA256SUM.sig https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
  - curl -fsSLo ${HOME}/codecov https://uploader.codecov.io/latest/linux/codecov
  - gpgv ${HOME}/codecov.SHA256SUM.sig ${HOME}/codecov.SHA256SUM
  - pushd ${HOME} && shasum -a 256 -c codecov.SHA256SUM && popd
  - pwd
  - chmod +x ${HOME}/codecov
  - ${HOME}/codecov --version
  - pip install nox

script:
  - nox -s tests-3.9

after_success:
  - ${HOME}/codecov

cache:
  directories:
    - $HOME/.cache/auditwheel_tests
