name: Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-commit checks (Black, Flake8, MyPy, ...)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.1

  test-dist:
    name: Test SDist & wheel
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install CPython 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          architecture: x64
      - name: Run tests
        run: pipx run nox -s test-dist -- 3.9

  test:
    name: CPython ${{ matrix.python }}
    needs: test-dist
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.9"
          - python: "3.10"
          - python: "3.11"
          - python: "3.12"
          - python: "3.13"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/auditwheel_tests
          key: python${{ matrix.python }}-${{ hashFiles('**/test_manylinux.py') }}
          restore-keys: python${{ matrix.python }}-
      - name: Install CPython ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
          architecture: x64
          allow-prereleases: true
      - name: Run tests
        run: pipx run nox -s tests-${{ matrix.python }}
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
